name: Express TypeScript CI/CD - Klinik Pintar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

  # Example for deployment to a server using SSH:
  # since i have no cloud server for this test, i just comment it now
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Deploy to Server
  #     uses: easingthemes/ssh-deploy@v2.1.5
  #     env:
  #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #       SOURCE: './'
  #       REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  #       REMOTE_USER: ${{ secrets.REMOTE_USER }}
  #       TARGET: ${{ secrets.REMOTE_TARGET }}
